version: '3'

services:
  ldn-server:
    build: ./
    restart: always
    ports:
      - "30456:30456/udp"
      - "8080:8080"
  stun:
    build: ./Stun.Dockerfile
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
